// web/app/pages/topic/create.vue
<script setup lang="ts">
import { ref } from 'vue'

definePageMeta({
  layout: 'default'
})

const topicName = ref('')
const topicDescription = ref('')
const isPublic = ref(true)

const isSubmitting = ref(false)

async function handleSubmit() {
  if (!topicName.value.trim()) return

  isSubmitting.value = true

  // TODO: Call API to create topic
  console.log('Creating topic:', {
    name: topicName.value,
    description: topicDescription.value,
    isPublic: isPublic.value
  })

  setTimeout(() => {
    isSubmitting.value = false
    // Redirect to topic list
    navigateTo('/topic')
  }, 1000)
}
</script>

<template>
  <div class="max-w-[800px] mx-auto w-full animate-[fade-in_0.4s_ease-out]">
    <!-- Header -->
    <div class="mb-6">
      <div class="flex items-center gap-3">
        <div class="w-12 h-12 rounded-xl bg-cyan-500/10 flex items-center justify-center">
          <UIcon
            name="i-material-symbols-add-circle"
            class="w-7 h-7 text-cyan-500"
          />
        </div>
        <div>
          <h1 class="text-2xl font-black text-gray-900 dark:text-white">
            创建话题
          </h1>
          <p class="text-sm text-gray-500">
            创建一个新的社区话题
          </p>
        </div>
      </div>
    </div>

    <!-- Form -->
    <div class="bg-white/40 dark:bg-gray-900/40 backdrop-blur-md rounded-[30px] border border-white/30 dark:border-gray-800/50 shadow-sm overflow-hidden">
      <div class="p-6 space-y-6">
        <!-- Topic Name -->
        <div class="space-y-2">
          <label class="block text-sm font-bold text-gray-700 dark:text-gray-300">
            话题名称 <span class="text-red-500">*</span>
          </label>
          <div class="flex items-center bg-white/50 dark:bg-gray-800/50 rounded-2xl border border-white/30 dark:border-gray-700/50 focus-within:ring-2 focus-within:ring-cyan-500/50 focus-within:border-cyan-500/50 transition-all overflow-hidden">
            <span class="pl-4 pr-2 py-3 text-gray-400 font-bold select-none">#</span>
            <input
              v-model="topicName"
              type="text"
              placeholder="输入话题名称"
              class="flex-1 py-3 pr-4 bg-transparent text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none"
            >
          </div>
          <p class="text-xs text-gray-400">
            话题名称只能包含字母、数字和下划线
          </p>
        </div>

        <!-- Topic Description -->
        <div class="space-y-2">
          <label class="block text-sm font-bold text-gray-700 dark:text-gray-300">
            话题描述
          </label>
          <textarea
            v-model="topicDescription"
            rows="4"
            placeholder="描述这个话题的内容..."
            class="w-full px-4 py-3 bg-white/50 dark:bg-gray-800/50 rounded-2xl border border-white/30 dark:border-gray-700/50 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500/50 transition-all resize-none"
          />
        </div>

        <!-- Visibility -->
        <div class="space-y-2">
          <label class="block text-sm font-bold text-gray-700 dark:text-gray-300">
            可见性
          </label>
          <div class="flex gap-3">
            <button
              class="flex-1 flex items-center gap-3 p-4 rounded-2xl border-2 transition-all"
              :class="isPublic
                ? 'border-cyan-500 bg-cyan-50 dark:bg-cyan-500/10'
                : 'border-white/30 dark:border-gray-700/50 hover:border-cyan-500/50'"
              @click="isPublic = true"
            >
              <UIcon
                name="i-material-symbols-public"
                class="w-5 h-5"
                :class="isPublic ? 'text-cyan-500' : 'text-gray-400'"
              />
              <div class="text-left">
                <span class="block font-bold text-sm text-gray-900 dark:text-white">公开</span>
                <span class="block text-xs text-gray-500">所有人都可以看见</span>
              </div>
            </button>
            <button
              class="flex-1 flex items-center gap-3 p-4 rounded-2xl border-2 transition-all"
              :class="!isPublic
                ? 'border-cyan-500 bg-cyan-50 dark:bg-cyan-500/10'
                : 'border-white/30 dark:border-gray-700/50 hover:border-cyan-500/50'"
              @click="isPublic = false"
            >
              <UIcon
                name="i-material-symbols-lock"
                class="w-5 h-5"
                :class="!isPublic ? 'text-cyan-500' : 'text-gray-400'"
              />
              <div class="text-left">
                <span class="block font-bold text-sm text-gray-900 dark:text-white">私有</span>
                <span class="block text-xs text-gray-500">仅关注者可见</span>
              </div>
            </button>
          </div>
        </div>
      </div>

      <!-- Actions -->
      <div class="px-6 py-4 border-t border-white/20 dark:border-gray-800/50 flex items-center justify-end">
        <UButton
          label="创建话题"
          color="primary"
          class="rounded-full shadow-[0_0_15px_rgba(57,197,187,0.5)]"
          :loading="isSubmitting"
          :disabled="!topicName.trim()"
          @click="handleSubmit"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
@keyframes fade-in {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>

// web/src/app/topic/create/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/ui/Icon";
import { useI18n } from "@/components/providers/I18nProvider";

export default function TopicCreatePage() {
  const { t } = useI18n();
  const router = useRouter();
  const [topicName, setTopicName] = useState("");
  const [topicDescription, setTopicDescription] = useState("");
  const [isPublic, setIsPublic] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async () => {
    if (!topicName.trim()) return;
    setIsSubmitting(true);
    // TODO: Call API to create topic
    setTimeout(() => {
      setIsSubmitting(false);
      router.push("/topic");
    }, 1000);
  };

  return (
    <div className="flex flex-col h-full animate-[fadeIn_0.4s_ease-out]">
      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-3 shrink-0">
        <button
          onClick={() => router.back()}
          className="flex items-center justify-center w-8 h-8 rounded-full hover:bg-black/5 dark:hover:bg-white/5 transition-colors"
        >
          <Icon name="arrow_left" fontSize={18} />
        </button>
        <h2 className="text-base font-bold text-gray-900 dark:text-white">{t("topic.createTopic")}</h2>
      </div>

      {/* Form */}
      <div className="flex-1 overflow-y-auto px-4 pb-6">
        <div className="max-w-[600px] mx-auto bg-white/60 dark:bg-gray-800/40 backdrop-blur-sm rounded-3xl border border-gray-100 dark:border-gray-700/50 overflow-hidden shadow-sm">
          <div className="p-6 space-y-5">
            {/* Topic Name */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
                {t("topic.topicName")} <span className="text-red-400">*</span>
              </label>
              <div className="flex items-center bg-gray-50 dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 focus-within:ring-2 focus-within:ring-cyan-500/50 focus-within:border-cyan-500 transition-all overflow-hidden">
                <span className="pl-4 pr-2 py-3 text-gray-400 font-bold select-none">#</span>
                <input
                  type="text"
                  value={topicName}
                  onChange={(e) => setTopicName(e.target.value)}
                  placeholder={t("topic.enterTopicName")}
                  className="flex-1 py-3 pr-4 bg-transparent text-gray-900 dark:text-white text-sm placeholder-gray-400 focus:outline-none"
                />
              </div>
              <p className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 px-1">
                {t("topic.nameValidation")}
              </p>
            </div>

            {/* Description */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">{t("topic.topicDescription")}</label>
              <textarea
                value={topicDescription}
                onChange={(e) => setTopicDescription(e.target.value)}
                rows={4}
                placeholder={t("topic.describeTopic")}
                className="w-full px-4 py-3 bg-gray-50 dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white text-sm resize-none placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500 transition-all"
              />
            </div>

            {/* Visibility */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">{t("topic.visibility")}</label>
              <div className="flex gap-3">
                <button
                  onClick={() => setIsPublic(true)}
                  className={`flex-1 flex items-center gap-3 p-4 rounded-2xl border-2 transition-all ${
                    isPublic
                      ? "border-cyan-500 bg-cyan-50 dark:bg-cyan-500/10"
                      : "border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600"
                  }`}
                >
                  <Icon name="public" className={isPublic ? "text-cyan-500" : "text-gray-400"} fontSize={20} />
                  <div className="text-left">
                    <span className="block font-bold text-sm text-gray-900 dark:text-white">{t("topic.public")}</span>
                    <span className="block text-xs text-gray-500">{t("topic.visibleToAll")}</span>
                  </div>
                </button>
                <button
                  onClick={() => setIsPublic(false)}
                  className={`flex-1 flex items-center gap-3 p-4 rounded-2xl border-2 transition-all ${
                    !isPublic
                      ? "border-cyan-500 bg-cyan-50 dark:bg-cyan-500/10"
                      : "border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600"
                  }`}
                >
                  <Icon name="lock" className={!isPublic ? "text-cyan-500" : "text-gray-400"} fontSize={20} />
                  <div className="text-left">
                    <span className="block font-bold text-sm text-gray-900 dark:text-white">{t("topic.private")}</span>
                    <span className="block text-xs text-gray-500">{t("topic.onlyVisibleToYou")}</span>
                  </div>
                </button>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="px-6 py-4 border-t border-gray-100 dark:border-gray-800 flex items-center justify-end">
            <button
              onClick={handleSubmit}
              disabled={!topicName.trim() || isSubmitting}
              className="flex items-center gap-2 px-6 py-2.5 bg-gradient-to-r from-cyan-500 to-teal-400 text-white rounded-full text-sm font-bold shadow-lg shadow-cyan-500/25 hover:shadow-cyan-500/40 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
            >
              {isSubmitting ? (
                <Icon name="refresh" className="animate-spin" fontSize={16} />
              ) : (
                <Icon name="add" fontSize={16} />
              )}
              {t("topic.createTopic")}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
