// web/app/pages/settings/profile.vue
<script setup lang="ts">
import { useUserStore } from '~/stores/user'
import { useSystemStore } from '~/stores/system'
import { useAppToast } from '~/composables/useAppToast'

useHead({
  title: '本用户 | 设置'
})

const userStore = useUserStore()
const systemStore = useSystemStore()
const toast = useAppToast()
const isLoggingOut = ref(false)

async function handleLogout() {
  if (systemStore.isDevMode) {
    toast.add({
      title: '开发模式无法操作此功能',
      description: '该功能需要依赖真实服务端使用，无法进行测试',
      color: 'warning',
      icon: 'i-material-symbols-terminal'
    })
    return
  }

  if (isLoggingOut.value) return

  isLoggingOut.value = true
  try {
    await userStore.logoutAll()
    toast.add({
      title: '已安全登出',
      description: '所有设备已同时登出。',
      color: 'success',
      icon: 'i-material-symbols-check-circle'
    })
    navigateTo('/')
  } catch {
    toast.add({
      title: '登出失败',
      description: '请稍后重试。',
      color: 'error',
      icon: 'i-material-symbols-error'
    })
  } finally {
    isLoggingOut.value = false
  }
}

function handleClearCache() {
  toast.add({
    title: '缓存已清除',
    description: '本地存储已清理完毕。',
    color: 'success',
    icon: 'i-material-symbols-check-circle'
  })
}
</script>

<template>
  <div class="max-w-[800px] mx-auto space-y-8 pb-12 animate-[fade-in_0.3s_ease-out]">
    <!-- Header: Avatar (Left) & Banner (Right) -->
    <section class="flex flex-col sm:flex-row gap-6 items-stretch">
      <!-- Left: Avatar -->
      <div class="w-full sm:w-48 shrink-0 flex flex-col items-center justify-center bg-white dark:bg-gray-900 rounded-[30px] border border-gray-200 dark:border-gray-800 shadow-sm p-6 group/avatar relative">
        <div class="w-32 h-32 rounded-full ring-4 ring-gray-100 dark:ring-gray-800 shadow-xl overflow-hidden relative bg-white dark:bg-gray-800">
          <img
            src="https://avatars.githubusercontent.com/u/739984?v=4"
            class="w-full h-full object-cover"
            alt="User Avatar"
          >

          <!-- Modify Avatar Hover -->
          <div class="absolute inset-0 flex items-center justify-center bg-black/0 group-hover/avatar:bg-black/40 transition-all duration-300 z-10 cursor-pointer">
            <UButton
              icon="i-material-symbols-photo-camera"
              color="neutral"
              variant="ghost"
              class="opacity-0 group-hover/avatar:opacity-100 scale-90 group-hover/avatar:scale-100 hover:bg-white/20 transition-all rounded-full w-12 h-12 flex items-center justify-center text-white"
            />
          </div>
        </div>

        <!-- Decorate Button -->
        <UButton
          icon="i-material-symbols-auto-awesome"
          color="primary"
          label="装饰"
          size="xs"
          class="rounded-full shadow-lg font-bold mt-4 z-20"
        />
      </div>

      <!-- Right: Banner -->
      <div class="flex-1 bg-white dark:bg-gray-900 rounded-[30px] border border-gray-200 dark:border-gray-800 shadow-sm overflow-hidden relative group/banner min-h-[160px] sm:min-h-full cursor-pointer">
        <!-- Placeholder Banner Pattern -->
        <div class="absolute inset-0 bg-gradient-to-br from-cyan-400/20 to-primary-500/20" />

        <!-- Modify Banner Hover -->
        <div class="absolute inset-0 flex items-center justify-center bg-black/0 group-hover/banner:bg-black/20 backdrop-blur-0 group-hover/banner:backdrop-blur-[2px] transition-all duration-300 z-10">
          <UButton
            icon="i-material-symbols-image"
            label="修改横幅"
            color="neutral"
            variant="solid"
            class="opacity-0 group-hover/banner:opacity-100 scale-95 group-hover/banner:scale-100 transition-all shadow-lg rounded-full font-bold px-4 text-gray-900"
          />
        </div>
      </div>
    </section>

    <!-- Information Forms -->
    <section class="flex flex-col gap-5 w-full">
      <!-- Nickname -->
      <UFormGroup
        label="昵称"
        required
        class="w-full"
      >
        <UInput
          model-value="Yuna Ayase"
          placeholder="输入您的昵称"
          size="lg"
          class="font-bold text-lg w-full block"
          :ui="{ root: 'shadow-sm', base: 'bg-white dark:bg-gray-900 rounded-2xl w-full' }"
        />
      </UFormGroup>

      <!-- Bio / Description -->
      <UFormGroup
        label="个人简介"
        class="w-full"
      >
        <UTextarea
          model-value="一位技术党，iMikufans技术组一员。&#10;我是Yuna Ayase，爱好作编曲、搞编程立项、深入探索计算机领域的深渊。&#10;#Misskey #iMikufans #CyaniAgent"
          placeholder="介绍一下你自己..."
          :rows="5"
          size="lg"
          class="custom-scrollbar w-full block"
          :ui="{ root: 'shadow-sm', base: 'bg-white dark:bg-gray-900 rounded-2xl resize-none w-full' }"
        />
        <div class="flex justify-between items-center mt-2 px-1 w-full">
          <span class="text-[11px] text-gray-400 dark:text-gray-500">可以在个人简介中包含 #标签。</span>
          <UButton
            label="预览"
            variant="ghost"
            color="primary"
            size="xs"
          />
        </div>
      </UFormGroup>

      <!-- Location -->
      <UFormGroup
        label="位置"
        class="w-full"
      >
        <UInput
          model-value="/Data/Users/Yuna Ayase"
          icon="i-material-symbols-location-on"
          placeholder="您的位置"
          size="lg"
          class="w-full block"
          :ui="{ root: 'shadow-sm', base: 'bg-white dark:bg-gray-900 rounded-2xl w-full' }"
        />
      </UFormGroup>

      <!-- Birthday -->
      <UFormGroup
        label="生日"
        class="w-full"
      >
        <UInput
          icon="i-material-symbols-cake"
          placeholder="年 / 月 / 日"
          type="date"
          size="lg"
          class="w-full block"
          :ui="{ root: 'shadow-sm', base: 'bg-white dark:bg-gray-900 rounded-2xl w-full' }"
        />
      </UFormGroup>

      <!-- Language -->
      <UFormGroup
        label="语言"
        class="w-full"
      >
        <USelectMenu
          :options="['自动跟随浏览器', '简体中文', 'English', '日本語']"
          model-value="简体中文"
          size="lg"
          class="w-full block"
          :ui="{ base: 'bg-white dark:bg-gray-900 rounded-2xl shadow-sm w-full' }"
        />
      </UFormGroup>

      <!-- Additional Info Fields Accordion -->
      <UFormGroup class="w-full mt-2">
        <UButton
          icon="i-material-symbols-list"
          label="附加信息编辑"
          color="neutral"
          variant="soft"
          size="lg"
          class="w-full justify-between items-center rounded-2xl bg-white dark:bg-gray-900 shadow-sm text-gray-700 dark:text-gray-300 font-bold"
          trailing-icon="i-material-symbols-keyboard-arrow-down"
        />
      </UFormGroup>
    </section>

    <!-- Account Actions -->
    <section class="mt-8 pt-8 border-t border-gray-200 dark:border-gray-800 flex flex-col gap-3">
      <h3 class="text-xs font-black text-gray-400 dark:text-gray-500 uppercase tracking-widest pl-2 mb-2">
        账户管理
      </h3>

      <UButton
        icon="i-material-symbols-settings"
        label="设置的配置"
        color="neutral"
        variant="ghost"
        size="lg"
        class="w-full justify-start rounded-2xl hover:bg-black/5 dark:hover:bg-white/5 font-bold"
      />
      <UButton
        icon="i-material-symbols-delete"
        label="清除缓存"
        color="neutral"
        variant="ghost"
        size="lg"
        class="w-full justify-start rounded-2xl hover:bg-black/5 dark:hover:bg-white/5 font-bold"
        @click="handleClearCache"
      />
      <div class="pt-4">
        <UButton
          icon="i-material-symbols-power-settings-new"
          label="登出此帐号"
          color="error"
          variant="soft"
          size="lg"
          :loading="isLoggingOut"
          class="w-full justify-center rounded-[20px] font-black text-base transition-transform hover:scale-[1.02] active:scale-95 shadow-sm py-3"
          @click="handleLogout"
        />
      </div>
    </section>
  </div>
</template>

// web/src/app/settings/profile/page.tsx
"use client";

import { useState } from "react";
import Image from "next/image";
import { useUserStore } from "@/stores/user";
import { useSystemStore } from "@/stores/system";
import { Icon } from "@/components/ui/Icon";
import { useI18n } from "@/components/providers/I18nProvider";

export default function ProfileSettingsPage() {
  const { t } = useI18n();
  const userStore = useUserStore();
  const systemStore = useSystemStore();
  const [isLoggingOut, setIsLoggingOut] = useState(false);
  const [nickname, setNickname] = useState(userStore.user?.name || "");
  const [bio, setBio] = useState("");
  const [location, setLocation] = useState("");
  const [birthday, setBirthday] = useState("");
  const [language, setLanguage] = useState("简体中文");
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleLogout = async () => {
    if (systemStore.isDevMode) return;
    if (isLoggingOut) return;
    setIsLoggingOut(true);
    try {
      await userStore.logoutAll();
    } catch {
      // silently fail
    } finally {
      setIsLoggingOut(false);
    }
  };

  const handleClearCache = () => {
    localStorage.clear();
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  return (
    <div className="max-w-[700px] mx-auto p-6 space-y-8 animate-[fadeIn_0.3s_ease-out]">
      {/* Header */}
      <div className="flex items-center gap-4">
        <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-cyan-500 to-teal-400 flex items-center justify-center shadow-lg shadow-cyan-500/20">
          <Icon name="person" className="text-white" fontSize={24} />
        </div>
        <div>
          <h1 className="text-xl font-bold text-gray-900 dark:text-white">{t("settings.personalProfile")}</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">{t("settings.manageProfile")}</p>
        </div>
      </div>

      {/* Avatar & Banner */}
      <div className="flex flex-col sm:flex-row gap-4">
        {/* Avatar */}
        <div className="relative group w-full sm:w-40 shrink-0 flex flex-col items-center bg-white dark:bg-gray-900 rounded-3xl border border-gray-200 dark:border-gray-800 p-6">
          <div className="w-24 h-24 rounded-full overflow-hidden ring-4 ring-gray-100 dark:ring-gray-800 shadow-lg">
            {userStore.avatar ? (
              <Image src={userStore.avatar} width={96} height={96} className="w-full h-full object-cover" alt="Avatar" />
            ) : (
              <div className="w-full h-full bg-cyan-500/20 flex items-center justify-center">
                <Icon name="person" className="text-cyan-500" fontSize={36} />
              </div>
            )}
          </div>
          <button className="mt-3 flex items-center gap-1.5 px-3 py-1.5 bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 rounded-full text-xs font-semibold hover:bg-cyan-500/20 transition-colors">
            <Icon name="photo_camera" fontSize={14} />
            {t("settings.changeAvatar")}
          </button>
        </div>

        {/* Banner */}
        <div className="flex-1 relative bg-white dark:bg-gray-900 rounded-3xl border border-gray-200 dark:border-gray-800 overflow-hidden min-h-[140px] group cursor-pointer">
          <div className="absolute inset-0 bg-gradient-to-br from-cyan-400/20 to-teal-400/20" />
          <div className="absolute inset-0 flex items-center justify-center bg-black/0 group-hover:bg-black/20 transition-all">
            <span className="opacity-0 group-hover:opacity-100 flex items-center gap-2 px-4 py-2 bg-white/90 dark:bg-gray-900/90 rounded-full text-sm font-semibold text-gray-700 dark:text-gray-300 transition-all shadow-lg">
              <Icon name="image" fontSize={16} />
              {t("settings.changeBanner")}
            </span>
          </div>
        </div>
      </div>

      {/* Form Fields */}
      <div className="space-y-5">
        {/* Nickname */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
            {t("settings.nickname")} <span className="text-red-400">*</span>
          </label>
          <input
            type="text"
            value={nickname}
            onChange={(e) => setNickname(e.target.value)}
            placeholder={t("settings.enterNickname")}
            className="w-full px-4 py-3 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500 transition-all"
          />
        </div>

        {/* Bio */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
            {t("settings.bio")}
          </label>
          <textarea
            value={bio}
            onChange={(e) => setBio(e.target.value)}
            placeholder={t("settings.bioPlaceholder")}
            rows={4}
            className="w-full px-4 py-3 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl text-gray-900 dark:text-white text-sm resize-none focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500 transition-all"
          />
          <p className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 px-1">
            {t("settings.bioHint")}
          </p>
        </div>

        {/* Location */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
            {t("settings.location")}
          </label>
          <div className="relative">
            <Icon name="location_on" className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" fontSize={18} />
            <input
              type="text"
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              placeholder={t("settings.yourLocation")}
              className="w-full pl-10 pr-4 py-3 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500 transition-all"
            />
          </div>
        </div>

        {/* Birthday */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
            {t("settings.birthday")}
          </label>
          <div className="relative">
            <Icon name="cake" className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" fontSize={18} />
            <input
              type="date"
              value={birthday}
              onChange={(e) => setBirthday(e.target.value)}
              className="w-full pl-10 pr-4 py-3 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500 transition-all"
            />
          </div>
        </div>

        {/* Language */}
        <div>
          <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
            {t("settings.language")}
          </label>
          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
            className="w-full px-4 py-3 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-cyan-500/50 focus:border-cyan-500 transition-all appearance-none"
          >
            <option>{t("settings.autoFollowBrowser")}</option>
            <option>简体中文</option>
            <option>English</option>
            <option>日本語</option>
          </select>
        </div>
      </div>

      {/* Save Button */}
      <button
        onClick={handleSave}
        className={`w-full py-3 rounded-2xl font-bold text-sm transition-all ${
          saved
            ? "bg-green-500 text-white"
            : "bg-gradient-to-r from-cyan-500 to-teal-400 text-white shadow-lg shadow-cyan-500/25 hover:shadow-cyan-500/40 hover:scale-[1.01]"
        }`}
      >
        {saved ? t("settings.saved") : t("settings.saveChanges")}
      </button>

      {/* Account Actions */}
      <div className="pt-6 border-t border-gray-200 dark:border-gray-800 space-y-3">
        <h3 className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider px-1">
          {t("settings.accountManagement")}
        </h3>
        <button
          onClick={handleClearCache}
          className="w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors text-left"
        >
          <Icon name="delete" fontSize={18} />
          {t("settings.clearLocalCache")}
        </button>
        <button
          onClick={handleLogout}
          disabled={isLoggingOut}
          className="w-full flex items-center justify-center gap-2 py-3 rounded-2xl bg-red-500/10 text-red-500 font-bold text-sm hover:bg-red-500/20 transition-all active:scale-95"
        >
          {isLoggingOut ? (
            <Icon name="refresh" className="animate-spin" fontSize={16} />
          ) : (
            <Icon name="power_settings_new" fontSize={16} />
          )}
          {t("settings.logoutAccount")}
        </button>
      </div>
    </div>
  );
}
